export {
  IconBrandWhatsapp,
  IconArrowRight,
  IconArrowLeft,
  IconX,
  IconChevronLeft,
  IconChevronRight,
  IconMenu2,
  IconEye,
  IconStar,
  IconUser,
  IconRefresh,
  IconEdit,
  IconTrash,
  IconPlus,
  IconCheck,
  IconLoader2,
  IconPhoto,
  IconGripVertical,
  IconLogout,
  IconSettings,
  IconPackage,
  IconTag,
  IconFileText,
  IconLayoutDashboard,
  IconKey,
} from "@tabler/icons-react";
